### PR TITLE
Make the USACS logo the correct size on the mission, mentors, and out…

### PR DESCRIPTION
**Pull request by peter-bandziukas**
…reach pages

### CODE REVIEW

**Comment by hemangandhi** [comment]
Good catch! Thank you! :1st_place_medal:

**Comment by k3v** [comment]
I think this pull request introduces new errors such as the unbounded image on the outreach page at the moment.

**Comment by peter-bandziukas** [comment]
Yeah, it looks like it does. Sorry about that, I really should have caught it before making a PR. I committed a fix to my fork, do I need to make a new pull request for that?

**Comment by k3v** [comment]
👍

**Pull request merged**
