### PR TITLE
Added page titles and fixed awkward excess right scrolling on mentors page

### PR DESCRIPTION
**Pull request by k3v**

### CODE REVIEW

**Comment by k3v** [comment]
I'm tryna cop Hacktoberfest pull requests :)

**Comment by hemangandhi** [comment]
Nice! Thank you! :100:

**Comment by mjrb** [comment]
I was looking though merge request to make sure I don't get too far behind and I think you edited the actual bootstrap library?

**Comment by k3v** [comment]
Hmm I see that would pose a problem. That was careless of me. I'll submit a new pull request.

**Pull request merged**
