### PR TITLE
refactoring for templates while hopefuly preserving any missed comits

### PR DESCRIPTION
**Pull request by mjrb**
i refactored the site for templates but started behind like an idiot :( i added all of the functionality of the missed commits but if this auto merges its gonna get really messed up

### CODE REVIEW

**Comment by hemangandhi** [comment]
I'll try to fix it some time.

**Comment by mjrb** [comment]
I cant even do this properly from the github website. I really need some help

**Comment by hemangandhi** [comment]
OK... so what did you change?

Because I don't actually understand what you did. I see the layout but I'm not 100% sure of 2 things:
1. Does the compiler now generate what is on master?
2. Can we gitignore all of the .html pages?

**Comment by mjrb** [comment]
1. yes the HTML files in master get generated and changed every time you compile.
2. Probably not, unless we somehow get git to automatically compile and deploy for us. If that can't be figured out then each patch would need to be compiled before pushing, or we could do a bunch of patches and then compile into a release ourselves.

Essentially what I think we may have to do is roll back the 10 commits that my branch was behind and then merge. Which is fine because I added some commits to get the functionality I missed

**Comment by hemangandhi** [comment]
Looks like we're forced to either learn Jekyll or keep the HTML around. https://help.github.com/articles/using-a-static-site-generator-other-than-jekyll/

I'll figure out the merging, because there are some minor fixes I needed to make to the Python code and build instructions. I think a rebase would come in handy!

**Comment by hemangandhi** [comment]
So I have some tweaks for this... I could PR onto your repo for the tweaks or fix the merging and PR here. Do you have a preference?

**Comment by mjrb** [comment]
For usacs or compile.py?

Also Once apon I time the site was built on Jekyll and I found it while I was building compile.py, but I decided against it because it involved more refactoring

**Comment by hemangandhi** [comment]
The tweaks are mostly compile.py things. Everything seems to build OK, though.

I added some docs about virtual environments because it's a python best-practice.

But like, I could also fix the merge.

**Comment by mjrb** [comment]
it would probably be best if you could just fix the merge, if you want i have a separate repo for compile.py that you could add your changes to too, I would greatly appreciate that.

**Comment by hemangandhi** [comment]
OK. I'll make a PR on your compile.py after fixing the merge here.

**Pull request merged**
