### PR TITLE
Resources Page

### PR DESCRIPTION
**Pull request by bigolu**
Uses a google sheet like the map. People can submit new resources and upon approval (which currently means putting a `1` in the approved column) they will appear on the site.

### CODE REVIEW

**Comment by hemangandhi** [comment]
Sorry for the delay in responding... HackRU's almost ready...

Can you add a link in index.html too?

**Comment by bigolu** [comment]
Sure thing, just added

**Comment by hemangandhi** [comment]
Is this good to merge, then?

**Comment by bigolu** [comment]
Yeah should be, but some point we should transfer the ownership of the Google Sheets over to USACS.

**Comment by hemangandhi** [comment]
Yeah... we'll discuss it. I assume the map form should be transferred too?

**Comment by bigolu** [comment]
yup

**Pull request merged**
